version: '3.8'

services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: sqlite3:///app/db/development.sqlite3
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/app/db

volumes:
  db_data:
